- README.md
> Updates README to describe NDC hub a little bit better

- .buildkite/pipeline.yml
https://hasurahq.atlassian.net/browse/INFRA-1059
> ci: use common build-node queue for buildkite

- Cargo.lock
- Dockerfile
- rust-connector-sdk/Cargo.toml
> Update `ndc-client` to 0.1.0-rc.2

- Cargo.lock
- rust-connector-sdk/Cargo.toml
- rust-connector-sdk/src/default_main.rs
- rust-connector-sdk/src/routes.rs
Update to support https://github.com/hasura/ndc-spec/pull/31
> Update ndc-spec to add error responses

- .envrc
- .envrc.local
- .github/workflows/nix.yaml
- .gitignore
- flake.lock
- flake.nix
Just for local development; no one's shipping anything with this thing.
> Set up a development shell with Nix.

- registry/sendgrid/metadata.json
- registry/typescript-deno/metadata.json
```
"repository":"https://github.com/hasura/ndc-sendgrid/",
"version":[
{
"tag": "v0.2",
"hash": "c0b3f13893e24a41df084985908af7ced0265498",
"is_verified": true
...
```
```
"repository":"https://github.com/hasura/ndc-typescript-deno/",
"version":[
{
"tag": "v0.2",
"hash":"37ef6c54fab8cae364fcfc320b0531b95bca6be8",
"is_verified":true
},
...
```
> Updating tags for Sendgrid and Typescript connectors in Connector Registry

- registry/clickhouse/metadata.json
- registry/sendgrid/metadata.json
Fixes some minor mistakes in metadata.json for Sendgrid and Clickhouse connectors
> registry: minor fixes

- .github/workflows/lint.yaml
- rust-connector-sdk/src/connector.rs
- rust-connector-sdk/src/default_main.rs
- rust-connector-sdk/src/routes.rs
I ran `cargo fmt` and `cargo clippy --fix`, and I've added jobs for CI so they can't be violated in the future.
> Lint and format.

- rust-connector-sdk/src/default_main.rs
Returning a valid error response on token validation failure.
> Set correct error response in token validation

- Cargo.lock
- rust-connector-sdk/Cargo.toml
- rust-connector-sdk/bin/main.rs
- rust-connector-sdk/src/connector.rs
- rust-connector-sdk/src/default_main.rs
- rust-connector-sdk/src/tracing.rs
> Add `resolved_configuration` in the response of the `/validate` API

- Cargo.lock
- rust-connector-sdk/Cargo.toml
- rust-connector-sdk/src/default_main.rs
Updates to `ndc-spec-v0.1.0-rc.8`
> Use latest ndc-spec, add test commands

- Cargo.lock
- rust-connector-sdk/Cargo.toml
- rust-connector-sdk/src/lib.rs
- rust-connector-sdk/src/secret.rs
- rust-connector-sdk/tests/json_schema/secret_value.jsonschema
> Add SecretValue enum

- Cargo.lock
- flake.nix
- rust-connector-sdk/Cargo.toml
- rust-connector-sdk/src/connector/example.rs
- rust-connector-sdk/src/default_main/v2_compat.rs
Notable changes:
- mutations were removed
- `source_collection_or_type` was removed
- `indexmap` was upgraded to version 2
> Upgrade ndc-spec and gdc_rust_types.

- Cargo.lock
- rust-connector-sdk/Cargo.toml
This PR updates the ndc-spec dependency to `v0.1.0-rc.13`
> update ndc-spec dependency

- registry/typescript-deno/metadata.json
Add the latest v0.24 version to the hub versions.
> Update TypeScript Deno connector version

- .github/workflows/test.yaml
I noticed we weren't. Not sure how important this is, but here's a job to do it.
> Run the tests in CI

- rfcs/0000-deployment.md
> Clarify use of OTEL_EXPORTER_OTLP_ENDPOINT

- rfcs/0001-packaging.md
[Rendered](https://github.com/hasura/ndc-hub/blob/rfc/packaging-spec/rfcs/0001-packaging.md)
> RFC: packaging spec

- registry/aurora/metadata.json
- registry/citus/metadata.json
- registry/cockroach/metadata.json
- registry/neon/metadata.json
- registry/postgres/metadata.json
- registry/yugabyte/metadata.json
Release notes: https://github.com/hasura/ndc-postgres/releases/tag/v0.5.1
> update ndc-postgres to v0.5.1

- registry/aurora/metadata.json
- registry/citus/metadata.json
- registry/cockroach/metadata.json
- registry/neon/metadata.json
- registry/postgres/metadata.json
- registry/yugabyte/metadata.json
https://github.com/hasura/ndc-postgres/releases/tag/v0.5.2
> ndc-postgres v0.5.2

- registry/aurora/metadata.json
- registry/citus/metadata.json
- registry/cockroach/metadata.json
- registry/neon/metadata.json
- registry/postgres-alloydb/metadata.json
- registry/postgres-azure/metadata.json
- registry/postgres-cosmos/metadata.json
- registry/postgres-gcp/metadata.json
- registry/postgres-timescaledb/metadata.json
- registry/postgres/metadata.json
- scripts/update-ndc-postgres.sh
https://github.com/hasura/ndc-postgres/releases/tag/v0.6.0
> update ndc-postgres to v0.6.0

- registry/clickhouse/README.md
Updating Clickhouse Hub page to include description of Clickhouse and include the correct deployment instructions.
> Damel clickhouse changes

- registry/clickhouse/metadata.json
> release clickhouse 0.2.7

- registry/aurora/README.md
- registry/aurora/metadata.json
- registry/citus/metadata.json
- registry/cockroach/metadata.json
- registry/neon/metadata.json
- registry/postgres-alloydb/README.md
- registry/postgres-alloydb/metadata.json
- registry/postgres-azure/README.md
- registry/postgres-azure/metadata.json
- registry/postgres-gcp/README.md
- registry/postgres-gcp/metadata.json
- registry/postgres-timescaledb/README.md
- registry/postgres-timescaledb/metadata.json
- registry/yugabyte/metadata.json
Changes Postgres to PostgreSQL in registry
> Changes Postgres to PostgreSQL in registry

- registry/aurora/README.md
- registry/aurora/metadata.json
- registry/citus/metadata.json
- registry/clickhouse/metadata.json
- registry/cockroach/metadata.json
- registry/mongodb/metadata.json
- registry/neon/metadata.json
- registry/postgres-alloydb/README.md
- registry/postgres-alloydb/metadata.json
- registry/postgres-azure/README.md
- registry/postgres-azure/metadata.json
- registry/postgres-gcp/README.md
- registry/postgres-gcp/metadata.json
- registry/postgres-timescaledb/README.md
- registry/postgres-timescaledb/metadata.json
- registry/yugabyte/metadata.json
Added some details to the MongoDB Hub section. TODO: When documentation is live a link to the docs should be added to the HUB page.
> MongoDB Hub Release

- rfcs/0005-docker-cli-plugin.md
[Rendered](https://github.com/hasura/ndc-hub/blob/daniel/rfc-docker-cli-plugin/rfcs/0005-docker-cli-plugin.md)
> Docker CLI plugin RFC

- registry/azure-cosmos/README.md
- registry/azure-cosmos/metadata.json
> Change Azure cosmos to Azure Cosmos NoSQL DB

- registry/aurora/metadata.json
- registry/citus/metadata.json
- registry/cockroach/metadata.json
- registry/neon/metadata.json
- registry/postgres-alloydb/metadata.json
- registry/postgres-azure/metadata.json
- registry/postgres-cosmos/metadata.json
- registry/postgres-gcp/metadata.json
- registry/postgres-timescaledb/metadata.json
- registry/postgres/metadata.json
https://github.com/hasura/ndc-postgres/releases/tag/v0.8.0
> ndc-postgres v0.8.0

- registry/mongodb/metadata.json
https://github.com/hasura/ndc-mongodb/releases/tag/v1.0.0
> MongoDB v1.0.0

- registry/mysql/README.md
Name needs to be lowercase to work.
> Fix hub connector name

- registry/graphql/README.md
Updated it to follow the standard template (reference postgres and mongodb)
> update graphQL connector readme

- registry/aurora/metadata.json
- registry/citus/metadata.json
- registry/cockroach/metadata.json
- registry/neon/metadata.json
- registry/postgres-alloydb/metadata.json
- registry/postgres-azure/metadata.json
- registry/postgres-cosmos/metadata.json
- registry/postgres-gcp/metadata.json
- registry/postgres-timescaledb/metadata.json
- registry/postgres/metadata.json
https://github.com/hasura/ndc-postgres/releases/tag/v1.0.1
> ndc-postgres v1.0.1

- scripts/update-ndc-postgres.sh
https://hasurahq.slack.com/archives/C04NS5JCD8A/p1723455972067679
> Update update-ndc-postgres.sh registry -> registry/hasura

- registry/hasura/azure-cosmos/metadata.json
> update `metadata.json` of the azure-cosmos connector

- registry/hasura/turso/README.md
- registry/hasura/turso/metadata.json
- registry/hasura/turso/releases/v0.0.15/connector-packaging.json
- registry/hasura/turso/releases/v0.1.0/connector-packaging.json
This PR updates the turso connector metadata to version 0.1.0.
> Update turso connector to v0.1.0

- registry/hasura/qdrant/README.md
- registry/hasura/qdrant/metadata.json
- registry/hasura/qdrant/releases/v0.2.1/connector-packaging.json
- registry/hasura/qdrant/releases/v0.3.0/connector-packaging.json
This PR updates the qdrant connector metadata to version 0.3.0.
> Update qdrant connector to v0.3.0

- registry/hasura/duckdb/README.md
- registry/hasura/duckdb/metadata.json
- registry/hasura/duckdb/releases/v0.0.17/connector-packaging.json
- registry/hasura/duckdb/releases/v0.1.0/connector-packaging.json
This PR updates the duckdb connector metadata to version 0.1.0.
> Update duckdb connector to v0.1.0

- registry/hasura/singlestore/metadata.json
- registry/hasura/singlestore/releases/v0.0.2/connector-packaging.json
This PR updates the singlestore connector metadata to version 0.0.2.
> Update singlestore connector metadata to version 0.0.2

- registry/hasura/nodejs/metadata.json
- registry/hasura/nodejs/releases/v1.8.0/connector-packaging.json
Adds NodeJS Lambda Connector v1.8.0
> Add nodejs v1.8.0

- registry/hasura/go/README.md
- registry/hasura/go/metadata.json
- registry/hasura/go/releases/v1.3.1/connector-packaging.json
> release ndc-go v1.3.1

- registry/hasura/clickhouse/releases/v0.2.9/connector-packaging.json
- registry/hasura/go/releases/v0.5.2/connector-packaging.json
- registry/hasura/go/releases/v0.6.3/connector-packaging.json
- registry/hasura/go/releases/v1.1.2/connector-packaging.json
- registry/hasura/go/releases/v1.2.3/connector-packaging.json
- registry/hasura/go/releases/v1.3.1/connector-packaging.json
- registry/hasura/go/releases/v1.4.0/connector-packaging.json
- registry/hasura/go/releases/v1.5.1/connector-packaging.json
- registry/hasura/mongodb/releases/v0.0.3/connector-packaging.json
- registry/hasura/mysql/releases/v0.1.0/connector-packaging.json
- registry/hasura/oracle/releases/v0.1.0/connector-packaging.json
- registry/hasura/phoenix/releases/v1.0.0/connector-packaging.json
- registry/hasura/snowflake/releases/v0.1.0/connector-packaging.json
Noticed these inconsistencies while working on https://github.com/hasura/ddn-assets/pull/4
> fix sha256 checksum for some connectors

- .github/workflows/registry-updates-prod.yaml
- .github/workflows/registry-updates.yaml
This reverts commit fdb98e110c5a86148e39be23e31a997a6c150620.
> ci: turn on connector publication

- registry-automation/cmd/utils.go
1. Checks the HTTP response status to be 200 OK after downloading the tar ball.
2. While extracting the tgz file, output the stdout and the stderr in case of error.
> Minor fixes in the connector publishing automation

- .github/workflows/ddn-assets.yaml
- docker/data/Dockerfile
This packages up the data in ndc-hub as a docker image.
Sample build: https://github.com/hasura/ndc-hub/actions/runs/11504126541
Sample image: https://github.com/hasura/ndc-hub/pkgs/container/ndc-hub
> ci: build and push ndc-hub:data.<commit-sha> docker image

- .github/workflows/ddn-assets.yaml
- docker/data/Dockerfile
- docker/server/Caddyfile
- docker/server/Dockerfile
Example build: https://github.com/hasura/ndc-hub/actions/runs/11504635181/job/32024555973
Example image: https://github.com/hasura/ndc-hub/pkgs/container/ndc-hub/294770878?tag=data-server.2704da13c6dfe54b7b50a1f2b9cafecf343bab58
Try running 
```
docker run --rm -it -p 7070:80 ghcr.io/hasura/ndc-hub:data-server.2704da13c6dfe54b7b50a1f2b9cafecf343bab58
```
and visit localhost:7070 to check out the files
> ci: build and push data server image

- registry/hasura/go/metadata.json
- registry/hasura/go/releases/v1.6.0/connector-packaging.json
[Changelog](https://github.com/hasura/ndc-sdk-go/releases/tag/v1.6.0)
> Add Go connector v1.6.0

- registry/hasura/python/metadata.json
- registry/hasura/python/releases/v0.1.1/connector-packaging.json
Update the Python Lambda connector to the latest version
> add release 0.1.1

- registry/hasura/mongodb/metadata.json
- registry/hasura/mongodb/releases/v1.4.0/connector-packaging.json
> Release MongoDB version 1.4.0

- registry/hasura/python/metadata.json
- registry/hasura/python/releases/v0.1.2/connector-packaging.json
This fixes issues with Nullable Pydantic types.
> update to new version

- registry/hasura/python/metadata.json
- registry/hasura/python/releases/v0.1.3/connector-packaging.json
Updates the connector to the latest version
> update python version

- registry/hasura/mysql/metadata.json
- registry/hasura/mysql/releases/v1.0.6/connector-packaging.json
- registry/hasura/oracle/metadata.json
- registry/hasura/oracle/releases/v1.0.4/connector-packaging.json
- registry/hasura/snowflake/metadata.json
- registry/hasura/snowflake/releases/v1.0.3/connector-packaging.json
- MySQL v1.0.6
- Oracle v1.0.4
- Snowflake v1.0.3
> Update MySQL, Oracle, and Snowflake

- registry/hasura/mongodb/metadata.json
- registry/hasura/mongodb/releases/v1.5.0/connector-packaging.json
> Release MongoDB version 1.5.0

- registry/hasura/http/metadata.json
- registry/hasura/http/releases/v0.6.0/connector-packaging.json
[Changelog](https://github.com/hasura/ndc-http/releases/tag/v0.6.0)
> Release HTTP connector v0.6.0

- registry/hasura/http/metadata.json
- registry/hasura/http/releases/v0.6.1/connector-packaging.json
[Changelog](https://github.com/hasura/ndc-http/releases/tag/v0.6.1)
> Release HTTP connector v0.6.1

- registry/hasura/http/metadata.json
- registry/hasura/http/releases/v0.7.0/connector-packaging.json
[Changelog](https://github.com/hasura/ndc-http/releases/tag/v0.7.0)
> Release HTTP connector v0.7.0

- registry/hasura/duckdb/metadata.json
- registry/hasura/duckdb/releases/v0.1.2/connector-packaging.json
This updates the DuckDB connector
> update duckdb to v0.1.2

- registry/hasura/duckdb/README.md
- registry/hasura/duckdb/metadata.json
- registry/hasura/duckdb/releases/v0.1.3/connector-packaging.json
This PR updates the duckdb connector metadata to version 0.1.3.
> Update duckdb connector to v0.1.3

- registry/hasura/postgres/README.md
> Fix: Postgres ref

- registry/hasura/singlestore/metadata.json
- registry/hasura/singlestore/releases/v0.0.5/connector-packaging.json
This PR updates the singlestore connector metadata to version 0.0.5.
> Update singlestore connector to v0.0.5

- registry/hasura/clickhouse/metadata.json
- registry/hasura/clickhouse/releases/v1.1.0/connector-packaging.json
Commit in ndc-clickhouse: https://github.com/hasura/ndc-clickhouse/commit/bf29bc5a3d068dedfa75ae500fe73d5e101ce3b9
> Release ClickHouse v1.1.0

- registry/hasura/http/metadata.json
- registry/hasura/http/releases/v0.8.2/connector-packaging.json
[Changelog](https://github.com/hasura/ndc-http/releases/tag/v0.8.2)
> HTTP connector v0.8.2

- registry/hasura/elasticsearch/README.md
Updates the Elasticsearch README to match the convention listed in our MVP document.
> Docs: Update Elasticsearch README

- registry/hasura/mysql/README.md
Updates the MySQL README with optimistic updates for the new how-to guide.
> Docs: Update MySQL README

- registry/hasura/duckdb/README.md
Updates DuckDB README with optimistic updates for the new how-to guide from hasura/ddn-docs#945.
> Docs: Update DuckDB README

- registry/hasura/storage/README.md
- registry/hasura/storage/metadata.json
- registry/hasura/storage/releases/v0.1.0/connector-packaging.json
[Changelog](https://github.com/hasura/ndc-storage/releases/tag/v0.1.0)
> Release Storage connector v0.1.0

- registry/hasura/turso/README.md
Updates README to match conventions in MVP doc.
> Docs: Update Turso README

- registry/hasura/trino/README.md
Updates Trino README to be in line with recent MVP docs work.
> Docs: Update Trino README

- registry/hasura/stripe/README.md
Updates Stripe README to be in line with recent MVP docs work.
> Docs: Update Stripe README

- registry/hasura/qdrant/README.md
> Docs: Update Qdrant README

- registry/hasura/athena/metadata.json
- registry/hasura/athena/releases/v1.0.2/connector-packaging.json
Fixes parsing of timestamp fields in the introspection.
> Release athena v1.0.2

- connector-metadata-types/schema.json
- connector-metadata-types/src/connectorTypes.ts
- rfcs/0013-spec-version-in-connector-metadata.md
[Rendered](https://github.com/hasura/ndc-hub/blob/kc/spec-version-in-connector-metadata/rfcs/0013-spec-version-in-connector-metadata.md)
> Proposal to include the ndc spec version in connector-metadata.yaml

- registry/hasura/http/metadata.json
- registry/hasura/http/releases/v0.10.0/connector-packaging.json
[Changelog](https://github.com/hasura/ndc-http/releases/tag/v0.10.0)
> HTTP connector v0.10.0

- registry-automation/cmd/ci.go
- registry-automation/cmd/registry_db.go
- registry/hasura/postgres-promptql/metadata.json
- registry/hasura/postgres-promptql/releases/v1.0.2/connector-packaging.json
- registry/hasura/postgres-promptql/tests/snapshots/query1/request.graphql
This is a V2 ndc-spec version release.
> Release postgres v1.0.2

- registry/hasura/mysql-promptql/metadata.json
- registry/hasura/mysql-promptql/releases/v1.0.4/connector-packaging.json
Fixes native query creation in DDN workspace.
> Mysql promptql v1.0.4

- registry/hasura/go/metadata.json
- registry/hasura/go/releases/v1.10.0/connector-packaging.json
[Changelog](https://github.com/hasura/ndc-sdk-go/releases/tag/v1.10.0)
> Go connector v1.10.0

- registry/hasura/http/metadata.json
- registry/hasura/http/releases/v0.11.0/connector-packaging.json
[Changelog](https://github.com/hasura/ndc-http/releases/tag/v0.11.0)
> HTTP connector v0.11.0

- registry/hasura/openapi/README.md
> Docs: Fix OpenAPI ref

- registry/hasura/prometheus/metadata.json
- registry/hasura/prometheus/releases/v0.4.1/connector-packaging.json
[Changelog](https://github.com/hasura/ndc-prometheus/releases/tag/v0.4.1)
> Prometheus connector v0.4.1

- registry/hasura/http/metadata.json
- registry/hasura/http/releases/v0.12.0/connector-packaging.json
[Changelog](https://github.com/hasura/ndc-http/releases/tag/v0.12.0)
> HTTP connector v0.12.0

- registry/hasura/promptql-programs/README.md
- registry/hasura/promptql-programs/metadata.json
- registry/hasura/promptql-programs/releases/v0.2.0/connector-packaging.json
- registry/hasura/promptql-programs/tests/compose.yaml
Release https://github.com/hasura/ndc-promptql-programs/releases/tag/v0.2.0
> Publish promptql program v0.2.0
