- src/connector.rs
- src/default_main.rs
- src/routes.rs
When implementing metrics for Postgres NDC I found querying the connection pool a little trickier than I'd like. Because the connector had no idea when `/metrics` were being requested, I had to set up a timer thread to poll the connection pool every second or so, possibly needlessly.
This is a very rough sketch of an solution - the connector provides a function that takes the `State` plus the Prometheus `Registry` and updates all counters.
> Add `fetch_metrics` call for fetching metrics

- Cargo.lock
- Cargo.toml
- src/connector.rs
- src/default_main.rs
This adds a configuration server to `default_main` which can be run using `cargo run -- configuration serve`:
```sh
> cargo run -- configuration serve
Starting server on 0.0.0.0:9100
> # Get a minimal configuration
> curl http://0.0.0.0:9100              
null
> # Elaborate a configuration
> curl http://0.0.0.0:9100 -X POST -H 'Content-Type: application/json' -d 'null'       
null
> # Validate configuration
> curl http://0.0.0.0:9100/validate -X POST -H 'Content-Type: application/json' -d 'null' | jq .
{
"schema": {
"scalar_types": {},
"object_types": {},
"collections": [],
"functions": [],
"procedures": []
}
}
> # Get the JSON schema for the configuration
> curl http://0.0.0.0:9100/schema | jq .    
{
"$schema": "http://json-schema.org/draft-07/schema#",
"title": "Null",
"type": "null"
} …
```
> Add configuration server to default_main

- src/lib.rs
The Connector trait uses model types from ndc-client in its signatures, but before this change ndc-hub does not re-export those types. That means that projects using ndc-hub also needed a direct dependency on ndc-client. That is complicated by the fact that the ndc-hub Cargo.toml locks a specific git hash for its ndc-client dependency. A consumer of ndc-hub would have to copy the same git hash in its Cargo.toml to avoid multiple copies of ndc-client, and would have to update that hash whenever the hash in ndc-hub changes.
Re-exporting types sidesteps this problem - consumers of ndc-hub no longer need to list ndc-client as a dependency. This way models can be imported as `use ndc_hub::models::CapabilitiesResponse;`
But I also want to argue that ndc-hub *should not* lock a revision of …
> feat: re-export ndc-client model types

- Cargo.lock
- Cargo.toml
- README.md
- src/connector.rs
- src/default_main.rs
Instead of using `axum_opentelemetry`, this PR wires up the tracing kit manually, so that we can use the existing CLI args, and have a bit more control over the subscriber/propagator/pipeline if we need it later.
> Alternative approach to tracing

- Cargo.lock
- Cargo.toml
- rust-connector-sdk/Cargo.toml
- rust-connector-sdk/bin/main.rs
- rust-connector-sdk/src/check_health.rs
- rust-connector-sdk/src/connector/example.rs
- rust-connector-sdk/src/default_main.rs
- rust-connector-sdk/src/lib.rs
- rust-connector-sdk/src/routes.rs
This allows us to add health checks to any `ndc-sdk`-based connector's Docker image without having to bundle `curl`.
I added a `check-health` command that checks `<HOST>:<PORT>/health` and prints an error if it fails. It defaults to `localhost:8100`, and uses the `PORT` environment variable if it's set, for easier `exec`-ing inside a Docker container.
I also modified the `/health` endpoint to report the error given in the response body.
It does this by checking that the HTTP status code is successful.
I also tidied up some other bits and bobs that got in my way.
> Add a command that checks the server's health on the port provided.

- Cargo.lock
- rust-connector-sdk/Cargo.toml
- rust-connector-sdk/src/default_main.rs
This is to be used in conjunction with the changes made to V3 engine that can send a pre-shared secret token via `Authorization: Bearer TOKEN` header.
If the `SERVICE_TOKEN_SECRET` env variable is set or the engine sends the `Authorization: Bearer SERVICE_TOKEN_SECRET` header, then the values must match.
If they do not match then the response will be StatusCode::UNAUTHORIZED.
If neither are set then the request proceeds as before.
> Adding SERVICE_TOKEN_SECRET to Rust SDK Serve command

- Cargo.lock
- rust-connector-sdk/src/default_main.rs
Docker containers are stopped by sending a SIGTERM. Ideally we would catch this and shut down gracefully rather just collapsing, or ignoring it and waiting for the SIGKILL 10 seconds later.
> Handle a SIGTERM correctly.

- rust-connector-sdk/src/connector.rs
- rust-connector-sdk/src/connector/example.rs
- rust-connector-sdk/src/default_main.rs
This PR adds `region_routings` as an argument to `validate_raw_configuration`. The `validate_raw_configuration` is supposed to create `Configuration` from `RawConfiguration`, but `Configuration` needs `region_routings`, which is not there in `RawConfiguration`.
This PR also adds functions to extract read and write regions from `Configuration`.
Please note that this is required for the multi-region routing project (see specs [here](https://docs.google.com/document/d/1qV8ZDxbnKzNn599eA_WbH3EU8z1aqQJN-RdQL1vF7W4/edit#heading=h.mmvzpxnp73aw))
> add `region_routing` in `validate_raw_configuration`

- Cargo.lock
- rust-connector-sdk/Cargo.toml
- rust-connector-sdk/src/default_main.rs
- rust-connector-sdk/src/default_main/v2_compat.rs
add `--enable_v2_compatibility` flag and env var. When enabled, a GDC server will be available under the `/v2` route.
Functionality is currently limited to mutations.
Some functionality is not supported, such as Array fields.
also had to conditionally remove sigterm handler so it would compile on windows
> add v2 compatibility layer

- rust-connector-sdk/src/default_main.rs
This allows us to use the `check-health` command for the configuration server too.
> Add a health check for the configuration server that always passes.

- registry/typescript-deno/README.md
- registry/typescript-deno/metadata.json
Adding the new v0.8 changes:
* Faster startup and hibernation wakeup
* Error reporting improvements
* Only expose exported functions
> Adding TS Connector v0.8 Tag changes

- rust-connector-sdk/src/default_main/v2_compat.rs
Update config schema for v2 compatibility mode to make `service_token_secret` optional.
Was previously nullable, (still is), but aparenlty the UI does not care.
This does still cause UI issues when `service_token_secret` is absent but those should be fixed eventually?
> make service_token_schema key not required

- README.md
The readme links to v2 connectors, which can be missleading.
This PR changes these links to point to public v3 connectors instead.
The postgres connector is not public (yet?) so we don't point to it for now.
> point to v3 connectors instead of v2 connectors

- rust-connector-sdk/src/default_main.rs
This adds `service_name` and `otlp_endpoint` to the serve configuration command, so that we can emit traces when running as a config server.
> chore: enable tracing in config server

- rust-connector-sdk/src/connector.rs
- rust-connector-sdk/src/connector/example.rs
This PR removes the `get_x_region` methods from the `Connector` trait.
> remove `get_x_region`

- rust-connector-sdk/src/connector.rs
- rust-connector-sdk/src/connector/example.rs
- rust-connector-sdk/src/default_main.rs
There are certain functions in the `Connector` trait that use the raw configuration, and accept a reference. We don't actually need to keep the configuration around in the SDK so we can pass by value here, which means that the relevant functions can own the data if they require it.
Making these input parameters values rather than references allows us to avoid cloning in other locations later.
> Move configuration when we don't need to hold onto it.

- Cargo.lock
- rust-connector-sdk/Cargo.toml
- rust-connector-sdk/src/connector.rs
- rust-connector-sdk/src/connector/example.rs
- rust-connector-sdk/src/default_main.rs
- rust-connector-sdk/src/default_main/v2_compat.rs
- rust-connector-sdk/src/json_response.rs
- rust-connector-sdk/src/lib.rs
- rust-connector-sdk/src/routes.rs
This introduces a new enum, `JsonResponse`, which is designed to supplant `axum::Json`. It implements `axum::IntoResponse`.
It has two variants:
1. `Value`, which behaves the same as `axum::Json`.
2. `Serialized`, which allows the connector to provide already-serialized JSON in the form of a `Bytes` value.
The latter can be used to construct the JSON directly in the database and avoid deserialization and re-serialization.
This is a breaking change, as at the very least, the connector implementations will now need to wrap responses in `JsonResponse::Value`. Hopefully it's not too much of a big deal.
There is a helper function, `JsonResponse::into_value`, used to deserialize the serialized bytes in certain situations. This is because the v2 compatibility layer and the connector used for …
> Introduce a "fast path" for returning already-serialized JSON.

- registry/typescript-deno/README.md
Fixes: https://github.com/hasura/ndc-typescript-deno/issues/39
> Updating TS Connector Docs for v0.9 tag

- rust-connector-sdk/src/tracing.rs
It does not exist. What even is this.
> Remove the deployment ID from the trace.

- Cargo.lock
- rust-connector-sdk/Cargo.toml
This is mostly for _ndc-client_ and _ndc-test_, but that requires a few more upgrades, and it seemed fine to just allow it.
I skipped `indexmap` as it's a major upgrade, but I may come back to it later.
I removed `axum-macros` and `uuid` as they were unused.
> Upgrade all SDK dependencies.

- rust-connector-sdk/src/connector.rs
- rust-connector-sdk/src/connector/example.rs
- rust-connector-sdk/src/default_main.rs
- rust-connector-sdk/src/lib.rs
- rust-connector-sdk/src/metrics.rs
- rust-connector-sdk/src/routes.rs
https://hasurahq.atlassian.net/browse/NDAT-1006
We'd like to track the status codes returned by a connector in metrics.
From the metrics registry created by ndc-sdk, create a metrics struct that will contain a counter for each status code we [want to track](https://hasura.github.io/ndc-spec/specification/error-handling.html), and increment those on each relevant API call (query, explain, etc.). We also include group buckets for 1xx, 2xx, etc.
An alternative to this approach would be to create a middleware that would count all responses, though these will also include health checks, missing api calls, metrics api calls, etc. Which I thought would muddle the metrics we actually care about.
We also add a new function to the Connector trait - `fn connector_name() -> String`, so we can use it …
> Add status code metrics

- rust-connector-sdk/src/connector.rs
- rust-connector-sdk/src/default_main.rs
- rust-connector-sdk/src/default_main/v2_compat.rs
- rust-connector-sdk/src/secret.rs
- rust-connector-sdk/src/tracing.rs
They were kind of all over the place, so I've gone for:
1. `std`
2. everything else
3. `crate`
> Organize the imports consistently.

- Cargo.lock
- rust-connector-sdk/Cargo.toml
- rust-connector-sdk/src/default_main.rs
- rust-connector-sdk/src/json_rejection.rs
- rust-connector-sdk/src/lib.rs
- rust-connector-sdk/src/routes.rs
[We'd like](https://hasurahq.slack.com/archives/C04NS5JCD8A/p1697618175968319?thread_ts=1697551776.418919&cid=C04NS5JCD8A) to return a json [ErrorResponse](https://hasura.github.io/ndc-spec/reference/types.html#errorresponse) on extract errors instead of plain text error messages.
With this PR, we'll return (for example):
```json
{
"message": "Parse error",
"details": "Failed to deserialize the JSON body into the target type: query.where.type: unknown variant `inary_comparison_operator`, expected one of `and`, `or`, `not`, `unary_comparison_operator`, `binary_comparison_operator`, `binary_array_comparison_operator`, `exists` at line 1 column 210"
}
```
We use [WithRejection](https://docs.rs/axum-extra/latest/axum_extra/extract/struct.WithRejection.html) to apply a transformation to the …
> return extraction errors as json ErrorResponse

- rust-connector-sdk/src/json_rejection.rs
We want to log when we cannot fundamentally make sense of the requests we receive.
> Log errors deserializing request bodies

- Cargo.lock
- rust-connector-sdk/Cargo.toml
- rust-connector-sdk/src/connector/example.rs
- rust-connector-sdk/src/default_main.rs
- rust-connector-sdk/src/default_main/v2_compat.rs
We want to start respecting connector capabilities in the engine, so we need them when building metadata in MBS using /validate.
> return capabilities in /validate

- rust-connector-sdk/src/tracing.rs
If there is no parent span ID, we something nonsensical, so we need to validate it.
Yes, this is hilarious.
> Only set the span parent ID if it is valid.

- Cargo.lock
- rust-connector-sdk/Cargo.toml
This PR updates the ndc-spec dependency to use the latest tag.
> update ndc-spec dependency to `v0.1.0-rc.12`

- registry/postgres/metadata.json
Pointing to https://github.com/hasura/ndc-postgres/releases/tag/v0.2.0
> update postgres connector registry

- rust-connector-sdk/src/connector.rs
- rust-connector-sdk/src/default_main/v2_compat.rs
- rust-connector-sdk/src/routes.rs
We want to be able to return 422 error codes on cases such as the following query:
```graphql
query MyQuery {
ArtistByArtistId(ArtistId: "") {
Name
}
}
```
Where the user provides an invalid value - `ArtistId` is expected to be an integer, but the user provided an empty string.
To do that we add a new error variant for QueryError, ExplainError and MutationError which will be mapped to that status code 422.
> Add an 'UnprocessableContent' error

- Dockerfile
Otherwise we're not testing what we expect.
> CI: Copy Cargo.lock into the build image to pin dependencies.

- rfcs/0000-deployment.md
- rfcs/0001-packaging.md
This is extracted from #89 in order to come to consensus on the aspects of packaging which are relevant only to deployment, while we figure out some of the specifics on the CLI side (watch mode etc.) in the existing RFC.
[Rendered](https://github.com/hasura/ndc-hub/blob/rfc/deployment-spec/rfcs/0000-deployment.md)
---
*Note:* I reverted some of the changes from the other PR:
- I think we agreed that that there is no harm in standardizing the config directory volume mount for all connectors, regardless of how they are built. I prefer this because it's simpler on the SDK side, and connectors can always choose not to use this directory.
- I want to reserve fewer environment variable "namespaces", and env vars can always be remapped in Docker config anyway, so I'm reverting `PORT` to …
> RFC: connector deployment spec

- Dockerfile
- rfcs/0000-deployment.md
- rust-connector-sdk/src/connector.rs
- rust-connector-sdk/src/connector/example.rs
- rust-connector-sdk/src/default_main.rs
- Use new environment variable names and defaults
- Remove configuration server
- Pass `PathBuf` to `validate_raw_configuration` and remove `RawConfiguration`
- Update `Dockerfile` to meet the deployment spec
> Update SDK for new deployment spec

- rust-connector-sdk/src/connector.rs
- rust-connector-sdk/src/connector/example.rs
We now need to conduct I/O during `parse_configuration`, which means the current `ValidateError` isn't quite enough.
I've renamed it to `ParseError` (to complement `parse_configuration`), and added a few extra cases.
1. `ParseError`, which denotes the file path and position where parsing failed.
2. `ValidateError`, as before, but including the file path, wrapping the vector in `InvalidNodes` so we can implement `Display`.
3. `IoError`, for when we fail to read a file.
4. `Other`, because I can't think of everything.
I am using the first 3 in integrating the latest changes into ndc-postgres.
> Rename and extend `ValidateError`.

- rust-connector-sdk/src/default_main.rs
I would like this for testing.
I also removed some `.unwrap()` calls for fun.
> Add a public constructor for `ServerState`.

- rust-connector-sdk/src/connector.rs
- rust-connector-sdk/src/connector/example.rs
- rust-connector-sdk/src/default_main.rs
These now receive access to `&self`, allowing us to inject further information into configuration.
A `default_main_with` function lets us provide alternative setups.
> Split out setup methods into their own trait.

- rust-connector-sdk/src/connector.rs
I experienced a very unhelpful error when I pointed to a configuration directory that _didn't_ contain a `configuration.json`. I'd like to add an error variant for this, and then use this variant in `ndc-postgres` when we update its version of `ndc-sdk`.
> Add a  specific error variant for missing configuration files

- Cargo.lock
- rust-connector-sdk/Cargo.toml
- rust-connector-sdk/src/default_main.rs
Updates ndc-spec and adds a bench subcommand for simple benchmarks of connectors built with the SDK:
```
Usage: ndc_hub_example bench [OPTIONS] --configuration <DIRECTORY> --snapshots-dir <DIRECTORY>
Options:
--configuration <DIRECTORY>  [env: HASURA_CONFIGURATION_DIRECTORY=]
--samples <COUNT>            the number of samples to collect per test [default: 100]
--tolerance <TOLERANCE>      tolerable deviation from previous report, in standard deviations from the mean
--snapshots-dir <DIRECTORY>  [env: HASURA_SNAPSHOTS_DIR=]
-h, --help                       Print help
```
> Update spec for test changes, add "bench" subcommand

- rfcs/0002-distribution-gh.md
RFC for distribution aspects of connectors.
Related specifications:
* [NDC specification](http://hasura.github.io/ndc-spec/)
* [Deployment Specification](https://github.com/hasura/ndc-hub/blob/main/rfcs/0000-deployment.md)
* [Packaging Specification (WIP)](https://github.com/hasura/ndc-hub/pull/89/files)
* [Umbrella specification](https://github.com/hasura/ndc-hub/pull/98)
While the precursor specifications outline the structure and mechanisms of packaging, this RFC outlines the initial distribution of package definitions.
See the [Rendered Version](https://github.com/hasura/ndc-hub/blob/lyndon/distribution-rfc-milestone-1/rfcs/0002-distribution-gh.md) of the RFC here.
> Distribution RFC (Milestone 1)

- .github/workflows/nix.yaml
- .gitignore
- Cargo.toml
- flake.lock
- flake.nix
- justfile
- rust-connector-sdk/Cargo.toml
This ensures the Nix shell uses the same Rust toolchain as `rustup`, and ensures we can build the package both with and without Nix.
> Set up a Nix build.

- rust-connector-sdk/src/default_main.rs
This is often useful for security reasons, e.g. only listening on localhost or an internal IP when the service is to be proxied.
It is also useful in testing on macOS, as running the service bound to a localhost IP (`127.0.0.1` or `::1`) means that the firewall will not be alerted, and so the test will not trigger an allow/deny prompt.
> Allow the operator to set the listening host IP address.

- Cargo.lock
- README.md
- rust-connector-sdk/Cargo.toml
- rust-connector-sdk/src/tracing.rs
- Currently, the OTEL exporter can't connect to HTTPS endpoints due to missing `tls` and `tls-roots` features. This PR enables them.
- By default, OTEL exporter shouldn't be enabled if `--otlp-endpoint` is empty. Currently the exporter is always running.
- Users can switch to HTTP protocol with `OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf`
- Upgrade the latest dependencies for `opentelemetry` packages.
- Allow configuring log level with `RUST_LOG` env variable.
> Support HTTP protocol and TLS for OpenTelemetry traces exporter

- rfcs/0001-packaging.md
[Rendered](https://github.com/hasura/ndc-hub/blob/daniel/dockerized-commands-rfc/rfcs/0001-packaging.md)
> Dockerized Commands in the packaging spec

- registry/clickhouse/metadata.json
Release clickhouse v0.2.3 with a bugfix for remote relationships
I'd mistakently downloaded and calculated the SHA for v0.2.1 and used that for v0.2.2
> Release clickhouse v0.2.3

- registry/nodejs-lambda/metadata.json
Adds the v1.4.1 of the NodeJS Lambda connector to the hub registry.
> Add NodeJS Lambda v1.4.1

- registry/qdrant/README.md
- registry/qdrant/metadata.json
Please review this update to the registry.
The Qdrant connector is located [here](https://github.com/hasura/ndc-qdrant).
Open Questions:
* I have pointed the package URI at the source code's .tar.gz file, which I performed a SHA256 hash on. Is this the correct thing to hash and point at?
* Some of the environment variables declared in my `connector-metadata.yaml` are optional. Is there a way to declare that to the CLI or will it ask for all of them?
* Have I correctly specified the "update" command in the connector-metadata and does it work? Will need to test this with the new beta CLI workflow.
> update qdrant registry metadata

- rfcs/0007-packaging-documentation-page.md
Add `documentationPage` to the packaging spec to link to connector specific getting started instructions to be shown by the CLI post running `ddn connector init`
Example:
```yaml
documentationPage: "https://hasura.io/docs/3.0/getting-started/build/add-business-logic?db=TypeScript"
```
[Rendered](https://github.com/hasura/ndc-hub/blob/ak/docs-page-packaging-spec/rfcs/0007-packaging-documentation-page.md)
> RFC: Add documentationPage to packaging spec

- .github/workflows/registry-updates.yaml
This PR extends the `registry-updates` workflow to access the repository secrets for forked repository PRs, like this [one](https://github.com/hasura/ndc-hub/pull/257) . 
It should be noted that, we are allowing this only for the staging environment and this is not needed for the production environment.
> Allow forked PRs to deploy connector version publishing in the staging environment

- .github/workflows/registry-updates.yaml
This PR fixes the logic of checking the approval status on the PR and uses the `github-script@v7` to do the same.
> Use the `github-script@v7` to correctly get the approval status on PR

- .github/workflows/registry-updates.yaml
This PR modifies the check out logic a bit for PRs opened on forked repositories. 
If the PR opened is from a forked repository, the code will be checked out to that repo's `ref` commit to access the files present in that branch, in the case the PR is opened directly in this repo, the behaviour will be the same as it was earlier.
> Fix bug in registry update automation

- registry/hasura/mongodb/README.md
The connector documentation URL has changed, and the link in the hub readme now goes to a 404. This PR updates the link to use the new URL.
> fix doc link in mongodb connector readme

- registry/hasura/qdrant/releases/v0.1.7/connector-packaging.json
- registry/hasura/qdrant/releases/v0.1.9/connector-packaging.json
We would like ndc-hub to be the one source of truth for all connector-related information. Adding these missing connector packaging files for realizing that goal.
> hasura/qdrant: add missing releases

- registry/hasura/cassandra/README.md
- registry/hasura/mysql/README.md
- registry/hasura/oracle/README.md
- registry/hasura/snowflake/README.md
Updates badges with mismatched names:
* Cassandra
* MySQL
* Oracle
* Snowflake
> Docs: Update badges

- rfcs/0006-connector-publishing-automation.md
We would like our versions to have the `v` prefix to avoid discrepancies with the other places. We did one round of cleanups already in the existing connector configurations. We will be soon introducing a CI check that performs this validation in pull requests.
> rfc: update semver to have version prefix

- registry/hasura/postgres/metadata.json
- registry/hasura/postgres/releases/v1.1.2/connector-packaging.json
Note: this uses a `v` prefix in the `version` field of the `connector-packaging.json` file.
This is most likely incorrect, but consistent with previous releases. We may fix this later.
> Release Postgres 1.1.2

- .github/workflows/ddn-assets.yaml
- docker/data/Dockerfile
Verified by
- triggering CI here: https://github.com/hasura/ndc-hub/actions/runs/11688699757/job/32549748749
- Running `docker run --rm -it -P ghcr.io/hasura/ndc-hub:data-server.5fd08ca16ddd05b8a73547ffba0bd533ce849917` and visiting the site exposed by it. It seem to have the right artifacts.
> ci: update ddn-assets version to v0.2.0

- .github/workflows/registry-updates.yaml
- registry-automation/cmd/ci.go
- registry-automation/cmd/ci_test.go
- registry-automation/cmd/registry_db.go
- registry-automation/cmd/types.go
- registry/hasura/azure-cosmos/metadata.json
Every time the connector's metadata.json file changes, the `latest_version`, `title` and `description` will be updated to the latest values in the registry DB.
> Record latest version, title and description if the connector metadata changes

- .github/workflows/ddn-assets.yaml
Refer https://github.com/hasura/ddn-assets/releases/tag/v0.2.1 for more details.
> ci: update ddn-assets version to v0.2.1

- registry/hasura/http/metadata.json
- registry/hasura/http/releases/v0.8.1/connector-packaging.json
[Changlog](https://github.com/hasura/ndc-http/releases/tag/v0.8.1)
> Release HTTP connector v0.8.1

- registry/hasura/duckdb/metadata.json
- registry/hasura/duckdb/releases/v0.1.4/connector-packaging.json
This PR updates the duckdb connector metadata to version 0.1.4.
> Update duckdb connector to v0.1.4

- .github/workflows/validate.yaml
- registry-automation/cmd/validate.go
- registry-automation/go.mod
- registry-automation/go.sum
- registry-automation/pkg/ndchub/ndchub.go
- registry-automation/pkg/validate/connector_packaging.go
- registry-automation/pkg/validate/connector_packaging_test.go
- registry/hasura/cassandra/releases/v1.0.7/connector-packaging.json
- registry/hasura/clickhouse/releases/v1.0.5/connector-packaging.json
- registry/hasura/duckdb/releases/v0.1.3/connector-packaging.json
- registry/hasura/duckdb/releases/v0.1.4/connector-packaging.json
- registry/hasura/postgres/releases/v1.2.0/connector-packaging.json
This PR introduces
- a `validate` command in the registry-automation program
- a GitHub action workflow that runs the validate command on every commit in the main branch and in pull requests
Additionally, I have made the CI checks to be needed for merging a PR.
> ci: validate contents of ndc-hub

- registry/hasura/duckdb/metadata.json
- registry/hasura/duckdb/releases/v0.1.6/connector-packaging.json
This PR updates the duckdb connector metadata to version 0.1.6.
> Update duckdb connector to v0.1.6

- registry/hasura/duckdb/metadata.json
- registry/hasura/duckdb/releases/v0.2.0/connector-packaging.json
This PR updates the duckdb connector metadata to version 0.2.0.
> Update duckdb connector to v0.2.0

- registry/hasura/python/README.md
- registry/hasura/python/metadata.json
- registry/hasura/python/releases/v0.1.6/connector-packaging.json
This PR updates the ndc-python-lambda connector metadata to version 0.1.6.
> Update ndc-python-lambda connector to v0.1.6

- registry/hasura/postgres/metadata.json
Noticed that this isn't upto date with what our current APIs return back when a `ddn connector init -i` is performed.
> postgres: update the latest version

- registry/hasura/go/metadata.json
- registry/hasura/go/releases/v1.8.0/connector-packaging.json
[Changelog](https://github.com/hasura/ndc-sdk-go/releases/tag/v1.8.0)
> Release Go connector v1.8.0

- registry/hasura/oracle/metadata.json
- registry/hasura/oracle/releases/v1.0.10/connector-packaging.json
This oracle connector version adds a placeholder native toolchain watch command.
> Release oracle connector with native toolchain watch

- registry/hasura/go/metadata.json
- registry/hasura/go/releases/v1.9.0/connector-packaging.json
[Changelog](https://github.com/hasura/ndc-sdk-go/releases/tag/v1.9.0)
> Release Go connector v1.9.0

- .github/workflows/registry-e2e-tests.yaml
- .github/workflows/registry-updates-prod.yaml
- .github/workflows/registry-updates.yaml
This Github Action is linked to a supply chain attack, updating to a fixed version.
https://www.infoworld.com/article/3849245/github-suffers-a-cascading-supply-chain-attack-compromising-ci-cd-secrets.html
> Bump `tj-actions/changed-files`

- .github/workflows/gokakashi-scan.yaml
- .github/workflows/pr-scan.yaml
- registry-automation/cmd/ci.go
- registry-automation/cmd/download_artifacts.go
- registry-automation/cmd/e2e.go
- registry-automation/cmd/root.go
- registry-automation/cmd/scan/gokakashi.go
- registry-automation/cmd/scan/scan.go
- registry-automation/cmd/scan/trivy.go
- registry-automation/cmd/utils.go
- registry-automation/cmd/validate.go
- registry-automation/go.mod
- registry-automation/go.sum
- registry-automation/main.go
- registry-automation/pkg/ndchub/packaging_spec.go
- registry-automation/pkg/ndchub/plugins_spec.go
- registry-automation/pkg/utils.go
- registry-automation/pkg/vulnerabilityscan/gokakashi.go
- registry-automation/pkg/vulnerabilityscan/trivy.go
This PR adds vulnerability scanning for new connector releases
Three new commands have been added:
1. `download-artifacts`: This command is responsible for downloading connector artifacts (CLI Plugins, targz file, Docker Images)
2. `scan trivy`: This command scans the downloaded connector artifacts using Trivy
3. `scan gokakashi`: This commands scans all connector docker images using Gokakashi
Trivy scan runs on new PRs
Gokakashi scan runs once a day periodically
This PR refactors and changes a few files. I've broken the changes down by commits. I'd recommend using commits to review this.
Tests for the new commands (and functions) are not yet present. I'll be adding them in a follow up PR
> add vulnerability scan

- registry/hasura/http/metadata.json
- registry/hasura/http/releases/v0.12.2/connector-packaging.json
[Changelog](https://github.com/hasura/ndc-http/releases/tag/v0.12.2)
> Release HTTP connector v0.12.2

- registry/hasura/go/metadata.json
- registry/hasura/go/releases/v2.0.0/connector-packaging.json
[Changelog](https://github.com/hasura/ndc-sdk-go/releases/tag/v2.0.0)
> Release Go connector v2.0.0

- registry/hasura/graphql/metadata.json
- registry/hasura/graphql/releases/v0.3.0/connector-packaging.json
[Changelog](https://github.com/hasura/ndc-graphql/releases/tag/v0.3.0)
> Release GraphQL connector v0.3.0
